# Generated by Django 3.2.8 on 2021-10-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_auto_20211015_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='current',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
