# Generated by Django 3.2.8 on 2021-10-16 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_auto_20211016_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 10, 10, 24, 779365), null=True),
        ),
        migrations.AlterField(
            model_name='current',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 10, 10, 24, 779365), null=True),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 10, 10, 24, 779365), null=True),
        ),
    ]
